### PR TITLE
Update builtbyus.jade

### PR DESCRIPTION
**Pull request by ghortiz-pena**
Maybe this changes the locations of the buttons, but be careful because I only have a vague idea of what I'm actually doing.

### CODE REVIEW

**Comment by celsom3** [comment]
This looks good, just remember that since this is hosted on GitHub pages, you need to compile the site to the root of the directory.

[https://github.com/Cosecha/cosecha.github.io#compiling-for-github-pages](https://github.com/Cosecha/cosecha.github.io#compiling-for-github-pages)

Just need to run a `gulp compile` and `gulp clean`  at the root of the repo to do so.

**Comment by celsom3** [comment]
@ghortiz-pena @thaismarques I went ahead and compile the changes.

**Comment by celsom3** [comment]
Thanks @ghortiz-pena for helping out with this! I really appreciate your support. 😄  👍

**Comment by ghortiz-pena** [comment]
Thanks @celsom3 for compiling, I didn't actually fork the whole repo, so I wasn't sure if I could do it remotely from the github website.

**Pull request merged**
